# **PyTorch Tutorial**
## CS4740/5740
## Fall 2023

______________________________________________________________________________________________________________________________________________________

Authors: Vinh Nguyen, Tushaar Gangavarapu; Adapted from last year's notebook by John R. Starr

Hello! In this notebook, we will introduce PyTorch, an essential machine learning framework for Python. Documentation for the package can be found [here](https://pytorch.org/docs/stable/index.html). Additional resources on how to use PyTorch can be found all around the Internet, though we strongly encourage you to fully explore all of the materials on the PyTorch website prior to moving to external sources.

This notebook assumes that you have already installed PyTorch on your device. If you have not yet installed PyTorch, please follow the instructions [here](https://pytorch.org/get-started/locally/).

Or if you need help setting up Google Colab, please follow the instructions here: https://www.dataquest.io/blog/getting-started-with-google-colab-for-deep-learning/

<a name="outline"></a>
## **Outline**
1. [What is PyTorch and Why Do We Use It?](#part1)
2. [Working with Tensors](#part2)
3. [Word Embeddings](#part3)
4. [Building a FFNN](#part4)

<a name="part1"></a>
[[^^^]](#outline)
## **Part 1: What is PyTorch and Why Do We Use It?**

PyTorch is a robust deep learning framework used by academics and researchers alike to advance scientific discoveries in a number of fields. Originally developed by researchers at Facebook (now Meta AI), PyTorch offers a straightforward pathway into the world of machine learning.

We are using PyTorch in this class for a number of reasons. First, PyTorch is very "pythonic" and easy-to-learn compared to some other machine learning frameworks. Second, the rich documentation and expansive community allow for less frustrations when it comes to developing and debugging models. Third, there are a number of behind-the-scenes operations that occur (namely, dynamic computation graphing) which helps us optimize our models and their training.

For more information on key features of PyTorch, please consider the following links:

1. [PyTorch Overview (Video)](https://www.youtube.com/watch?v=RwaVqvZ3xo8)
2. [Advantages of PyTorch in Comparison to Tensorflow (Video)](https://www.youtube.com/watch?v=nbJ-2G2GXL0)

<a name="part2"></a>
[[^^^]](#outline)
## **Part 2: Working with Tensors**

In this section, we'll go over the basic properties and operations on tensors. This is by no means an exhaustive list. If you _really_ want to get into the details, please see the PyTorch documentation [here](https://pytorch.org/docs/stable/index.html).

#### **2.1: Tensor Basics**

In [2]:
import torch
import numpy as np

# Setting a seed so we can all get the same numbers
torch.manual_seed(123)

Tensors are very easy to initialize! One way of doing so is by converting a list of numerical values:

In [3]:
# Converting list to tensor
data = [0, 10, 11]
t1 = torch.Tensor(data)
print(t1)
# Converting numpy array to tensor
data_from_numpy = np.random.rand(2,3)
t2 = torch.from_numpy(data_from_numpy)
print(t2)

tensor([ 0., 10., 11.])
tensor([[0.9522, 0.2911, 0.7107],
        [0.5114, 0.9698, 0.7821]], dtype=torch.float64)


In [4]:
# Examining aspects of our first tensor:
print(t1.type)
print(t1.shape)

print(t2.shape)

<built-in method type of Tensor object at 0x12fb9b2a0>
torch.Size([3])
torch.Size([2, 3])


However, _note the following_:

In [5]:
data_txt = ['The', 'dog', 'barked']

t_txt = torch.Tensor(data_txt)

ValueError: too many dimensions 'str'

Any idea what's going on in the cell above?

Finally, some other very useful ways to initialize tensors: rand, ones, and zeros

In [6]:
# Some ways to initialize tensors:
shape = (3, 2,)
t_rand = torch.rand(shape)
t_ones = torch.ones(shape)
t_zeros = torch.zeros(shape)

print(t_rand)
print(t_ones)
print(t_zeros)

tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


#### **2.2: Operations on Tensors**

While tensors are not lists, they do carry many similar properties of lists. You can slice them with indices:

In [7]:
print(t2, "\n")
# First row
print('First row of t2:', (t2[0]), "\n")

# Second column only
print('Second column only of t2:', t2[:, 1], "\n")

# Second row, third item
print('Second row, third item of t2:', t2[1, 2], "\n")

tensor([[0.9522, 0.2911, 0.7107],
        [0.5114, 0.9698, 0.7821]], dtype=torch.float64) 

First row of t2: tensor([0.9522, 0.2911, 0.7107], dtype=torch.float64) 

Second column only of t2: tensor([0.2911, 0.9698], dtype=torch.float64) 

Second row, third item of t2: tensor(0.7821, dtype=torch.float64) 



... and you can combine them (two different ways!):

In [8]:
# Two ways of combining tensors:
t3 = torch.Tensor([[1,2,3],
                   [4,5,6]])

t4 = torch.Tensor([[4,5,6],
                   [7,8,9]])

# Combining along a given dimension with torch.cat
t_cat90 = torch.cat((t3, t4), dim=0) # Totally not the Tompkins Consolidated Area Transport Bus 90
print(t_cat90)
print(t_cat90.shape)
print()

# Combining along a new dimension with torch.stack
t_stack_dim0 = torch.stack((t3, t4), dim=0)
print(t_stack_dim0)
print(t_stack_dim0.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([4, 3])

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[4., 5., 6.],
         [7., 8., 9.]]])
torch.Size([2, 2, 3])


In [9]:
# What do you think happens when we do...
t_cat92 = torch.cat((t3, t4), dim=1)
print(t_cat92)
print(t_cat92.shape)
print()

# And this...
t_stack_dim1 = torch.stack((t3, t4), dim=-1)
print(t_stack_dim1)
print(t_stack_dim1.shape)
print()

tensor([[1., 2., 3., 4., 5., 6.],
        [4., 5., 6., 7., 8., 9.]])
torch.Size([2, 6])

tensor([[[1., 4.],
         [2., 5.],
         [3., 6.]],

        [[4., 7.],
         [5., 8.],
         [6., 9.]]])
torch.Size([2, 3, 2])



Note the differences with the two methods above. Even though we are combining the same two tensors, we get output tensors of different dimensionalities. `torch.cat` takes two (or more) tensors and combines them along the specified dimension (default = 0). `torch.stack` takes two (or more) tensors and combines them along a NEW dimension. As its name suggests, `torch.stack` places two tensors on top of one another in a different dimension. Cool stuff! For more information on `torch.cat`, go [here](https://pytorch.org/docs/stable/generated/torch.cat.html); for more information on `torch.stack`, go [here](https://pytorch.org/docs/stable/generated/torch.stack.html).

Note, you can also use vstack or hstack if you don't want to mess around with the dimension parameter.

In [10]:
# What do you think gets outputted by the code below? The same as above or different...
t_vstack = torch.vstack([t3, t4])
print(t_vstack)
print(t_vstack.shape)
print()

t_hstack = torch.hstack([t3, t4])
print(t_hstack)
print(t_hstack.shape)
print()

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([4, 3])

tensor([[1., 2., 3., 4., 5., 6.],
        [4., 5., 6., 7., 8., 9.]])
torch.Size([2, 6])



We can also sum across multiple dimensions (default = 0):

In [11]:
# Summing
print(t3)
print()

# Across columns
print(t3.sum(dim=0))
print()

# Across rows
print(t3.sum(dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([5., 7., 9.])

tensor([ 6., 15.])


... and do do element multiplication:

In [13]:
# Element multiplication
t_em_1 = t3 * t4
t_em_2 = t3.mul(t4)

print(t_em_1)
print(t_em_2)

tensor([[ 4., 10., 18.],
        [28., 40., 54.]])
tensor([[ 4., 10., 18.],
        [28., 40., 54.]])


... along with matrix multiplication:

In [14]:
# Matrix multiplication
t_mm_1 = t3 @ t3.T # <- what's this ? any guesses ?
t_mm_2 = t3.matmul(t3.T)

print(t_mm_1)
print(t_mm_2)

tensor([[14., 32.],
        [32., 77.]])
tensor([[14., 32.],
        [32., 77.]])


Note that there are multiple ways of completing this operation. Let's talk about the differences between each.

In [22]:
# a quick aside on broadcasting
x = torch.empty(5,1,4,1)
y = torch.empty(  3,1,1)
z = x.matmul(y)

print(z.shape)

torch.Size([5, 3, 4, 1])


In [24]:
# mm - normal matrix mul
# bmm - batched + mm
# matmul - batched + broadcasting


t5 = torch.zeros((2,2))
t6 = torch.zeros((2,2))
t5[0,0] = 1
t5[1,1] = 1
t6[0,1] = 1
t6[1,0] = 1

print(t5)
print(t6)

print()

print(t5 @ t6, "\n")
print(t5.view(1,2,2).bmm(t6.view(1,2,2)), "\n")
print(t5.matmul(t6))

tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [1., 0.]])

tensor([[0., 1.],
        [1., 0.]]) 

tensor([[[0., 1.],
         [1., 0.]]]) 

tensor([[0., 1.],
        [1., 0.]])


Oh no! How should we go about solving this... let's look at a couple of important torch methods you might use in future homeworks and see if they'll be useful for this.
- transpose
- permute
- reshape
- clone
- view

Pssst, one final note, want to know the best part about learning these functions? The majority of the ones we used above (and many more from even further above) have their equivalents in numpy (sometimes even with the same function name)!.

In [ ]:
t7 = torch.rand(3,4,1)
print(t7)
print(t7.shape)
t7_transpose = torch.transpose(t7, 0, 1)
print(t7_transpose)
print(t7_transpose.shape)
t7_transpose[0,0,0] = 0
print(t7)
print()
t7_permute = torch.permute([1,0,2])
print(t7_permute)
print(t7_permute.shape)

Let's go back and fix the problem~

Finally, let's discuss PyTorch's in-place operations... Don't worry about seeing them for now, we'll have that opportunity further down the notebook!

<a name="part3"></a>
[[^^^]](#outline)
## **Part 3: Word Embeddings**

Now that we have become familiar with the basic concepts of tensors and their various properties, let's begin moving into NLP territory. As the title of this section indicates, we will begin our journey with word embeddings, an essential concept in NLP.

In [ ]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

As described in previous lectures, basic word embeddings serve as a computational approach to the distributional hypothesis: words that are similar to each other occur in similar contexts. These embeddings can then inform our model of various "semantic" features that are present in language data.

To provide a more practical example of how embeddings operate, consider the following nonsense sentences concerned with various kinds of aviation-related things:

In [ ]:
tiny_dataset = ['The helicopter engine broke through the rocket sky.',
                'The helicopter engine soared above the drone sky.',
                'The drone engine broke through the rocket sky'
                'The drone engine soared above the helicopter sky',
                'The drone engine knocked out the drone sky',
                'The rocket engine broke through the helicopter sky'
                'The rocket engine soared above the helicopter sky',
                'The rocket engine knocked out the helicopter sky',
                'The rocket engine shredded below the drone sky',
                'The bee wings broke through the goose sky.',
                'The bee wings soared above the goose sky.',
                'The bee wings knocked out the eagle sky.',
                'The eagle wings broke through the goose sky.',
                'The eagle wings soared above the eagle sky.',
                'The eagle wings knocked out the bee sky.',
                'The goose wings broke through the goose sky.',
                'The goose wings soared above the eagle sky.',
                'The jet wings soared above the bee sky.',
                'The jet engine broke through the jet sky.']

Wow -- that's a _lot_ of co-occurrences! Let's use this tiny, repetitive dataset to build very simple 2-dimensional embeddings based on counts.

For now, let's focus our attention on the machines ("helicopter", "drone", "rocket") and two contexts ("engine" and "sky"). To save some time, the following table shows the number of times that each machine appears next to "engine" and "sky":


|            | context: engine | context: sky |
|------------|-----------------|--------------|
| helicopter | 2               | 4            |
| drone      | 3               | 3            |
| rocket     | 4               | 2            |


For the purposes of this lecture, we will ignore that each machine is always followed by "the". I'll leave it up to you how this may (or may not) affect our embedding representation!


In this example, we can take each context in the table above as a dimension (x="engine", y="sky") and plot the coordinates for each machine according to its counts in each dimension:

![2d_embeddings](https://drive.google.com/uc?export=view&id=1HSmuy4Epym_dBBzXQScTs5LGZz7ScWZU)

In the graph above, we see that "helicopter" and "drone" are as close as "rocket" and "drone" (aka θ1 = θ2, where θ = cosine similarity. More on cosine similarity later!). However, "helicopter" and "rocket" appear to be further apart.


What if we consider more dimensions? Let's add "wings" to our contexts as a third dimension. For our words, let's add "bee", "eagle", "goose", and "jet". Our new table looks something like this:

|            | context: engine | context: sky | context: wings |
|------------|-----------------|--------------|----------------|
| helicopter | 2               | 4            | 0              |
| drone      | 3               | 3            | 0              |
| rocket     | 4               | 2            | 0              |
| bee        | 0               | 2            | 3              |
| goose      | 0               | 4            | 2              |
| eagle      | 0               | 3            | 3              |
| jet        | 1               | 1            | 1              |


We can then use a three-dimensional plot with axes x="engine", y="sky", and z="wings" to plot the counts of each word in context:


![3d_embeddings](https://drive.google.com/uc?export=view&id=1crOuM7Zqv8iFqew8-fUDFAIoDnHKQapP)

Above, we can see a clear difference in the vector representations between the words that co-occur with "wings" and those that do not. Cool stuff!


**An important note:** For the purposes of explication, we map a clear relationship in the two examples above: each context is a dimension, and each instance of a word in that context serves as a count, which in turn contributes to the word's exact vector representation. However, these vectors *do not* require such a clear mapping. Word embeddings with *n*-dimensions do not require an *n* that is equal to the total number of contexts. Instead, we can reduce (or increase) *n* to create more abstract, less interpretable dimensions. We will discuss this in the following sections!


#### **3.1 PyTorch embeddings**
Okay, enough with the background!

Previously, we mentioned that PyTorch tries to make your life easier. Let's get into the first example of it doing so! Consider the sentence "Hello class":

In [ ]:
# A very basic example:
word_to_ix = {"hello": 0, "class": 1}

To initialize embeddings, we can use `nn.Embedding` and specify two dimensions: the number of embeddings you need, and the dimensionality of the embeddings. Let's create embeddings of dimensions 2x5 (2 words in the vocab, each embedding has 5 dimensions):

In [ ]:
embeds = nn.Embedding(2, 5)  # 2 words in vocab, 5 dimensional embeddings

# Looking at class:
lookup_tensor = torch.tensor([word_to_ix["class"]], dtype=torch.long)     # Note that this is blank tensor of the words ids:
print(lookup_tensor)

# And then the embeddings initialize
hello_embed = embeds(lookup_tensor)
print(hello_embed)

Note that these are initialized embeddings are initialized randomly at first! If we want them to better approximate the semantics of our data, then we will need to undergo model training. At the moment, however, they will appear to be pretty random.

We now know how to create PyTorch embeddings. Woo hoo! However, how can we _analyze_ them? One method of doing so is checking the cosine similarity between two embeddings (see lecture slides for more information).

Luckily for us, PyTorch has a built-in CosineSimilarity function: `nn.CosineSimilarity`. While we would traditionally apply this function to word embeddings, _we will not do so here_ (don't worry, we will soon!), as we do not have trained embeddings. As such, we will use tensors to demonstrate cosine similarity. Let's initialize five tensors (feel free to mess around with these numbers to experiment with cosine similarity):

In [ ]:
# PyTorch's built-in Cosine Similarity function:
c1 = torch.Tensor([4,6,8])
c2 = torch.Tensor([4,7,8])
c3 = torch.Tensor([0,12,24])
c4 = torch.Tensor([-59, 78, -14])
c5 = torch.Tensor([16, 24, 32])
cosineSim = nn.CosineSimilarity(dim=0, eps=1e-6)

How do you think these will pattern? Which will be most similar? Which will be the least similar?

In [ ]:
# c1 compared to c2
print('c1, c2:', cosineSim(c1, c2))

# c1 compared to c3
print('c1, c3:', cosineSim(c1, c3))

# c1 compared to c4
print('c1, c4:', cosineSim(c1, c4))

# c1 compared to c5
print('c1, c5:', cosineSim(c1, c5))

For more information on `nn.Embedding`, look [here](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html). For more information on `nn.CosineSimilarity`, look [here](https://pytorch.org/docs/stable/generated/torch.nn.CosineSimilarity.html).

#### **3.2 An Example of Pre-trained Embeddings: GloVe Embeddings**

While it is essential to know how to train your own embeddings (as pertains to whatever task you are trying to complete), a number of pre-trained embeddings exist. In this tutorial, we will be using the GloVe embeddings as outlined in [Pennington et al. (2014)](https://nlp.stanford.edu/pubs/glove.pdf). Documentation for GloVe embeddings can be found [here](https://nlp.stanford.edu/projects/glove/).

First, we must download the GloVe embeddings. The following block of code will do this for you, but it may take some time to run!

In [ ]:
import torchtext

# The first time you run this will download a ~823MB file
glove = torchtext.vocab.GloVe(name="6B", # trained on Wikipedia 2014 corpus
                              dim=100)    # embedding size = 50

Thankfully for us, GloVe embeddings are _incredibly_ easy to use. All you need to do to find the embedding for a word is to look it up in the embedding dictionary:

In [ ]:
# Looking at an embedding for the word 'photograph'
print(glove['photograph'])

print(glove['photograph'].shape)

There are a number of ways to measure similarity between vectors (some of which can be found [here](https://developers.google.com/machine-learning/clustering/similarity/measuring-similarity). One way of doing so is by calculating the _Euclidean Distance_, which is captures the difference between the ends of vectors. The larger the Euclidean Distance, the further away the vectors are in semantic space. To calculate Euclidean Distance, we take the vector norm of the two tensors, which essentially calculates the difference between the vectors at each level of embedding.

In [ ]:
# Euclidean distance
x = glove['photograph']
y = glove['picture']
z = glove['sculpture']
print('EucDis between x, y:', torch.norm(y - x))
print('EucDis between x, z:', torch.norm(z- x))

We can also re-use our cosine similarity function from earlier to check out how similar the vectors are in semantic space:

In [ ]:
# Cosine sim

# Photograph & picture
print('CoSim between x, y:',cosineSim(x, y))

# Photograph & sculpture
print('CoSim between x, z:',cosineSim(x, z))

Let's move on to another example. Given the following, how do you think the cosine similarities will vary?

In [ ]:
# Note the following:
c = glove['cat']
k = glove['kitten']
d = glove['dog']

# Cat & kitten
print('CoSim between cat and kitten:', cosineSim(c, k))

In [ ]:
# Cat & dog
print('CoSim between cat and dog:', cosineSim(c, d))

Hold up! Let's _paws_ for a moment: why are cat & dog more similar than cat & kitten?

Let's try to pick apart which words are close to each other:

In [ ]:
# Function from this link: https://www.cs.toronto.edu/~lczhang/321/lec/glove_notes.html

# This function finds which words are closest to one another via Euclidean Distance:
def print_closest_words(vec, n=5):
    dists = torch.norm(glove.vectors - vec, dim=1)                # Compute Euclidean Distances to all words
    lst = sorted(enumerate(dists.numpy()), key=lambda x: x[1])    # Sort by distance
    for idx, difference in lst[1:n+1]: 					                  # Take the n most related words
        print(glove.itos[idx], difference)

In [ ]:
# Looking at cats!
print_closest_words(glove["cat"], n=10)

In [ ]:
# Looking at kitten
print_closest_words(glove["kitten"], n=10)

Here, the only carry-over between "cat" and "kitten" is "puppy". This suggests that "cat" and "kitten" have very different co-occurence distributions in the training data.

We can also implement some of the "vector math" from previous lectures:

In [ ]:
# The most famous word math example (include visualization)
print_closest_words(glove['king'] - glove['man'] + glove['woman'])

In [ ]:
# Any predictions about this one:
print_closest_words(glove['avian'] - glove['fly'])

While embeddings are certainly fun tools to play with, it's important to remember that there are some implicit biases encoded into their structure; this is a consequence of the data the embeddings were trained on. Consider the following examples:

In [ ]:
print_closest_words(glove['firefighter'] - glove['man'] + glove['woman'])

In [ ]:
print_closest_words(glove['firefighter'] - glove['woman'] + glove['man'])

<a name="part4"></a>
[[^^^]](#outline)
## **Part 4: Building a Feed Forward Neural Network (FFNN)**

It is now time to learn how to construct your first neural model! This section is a Frankensteinien creation from a couple different PyTorch tutorials found on the [Pytorch website tutorials](https://pytorch.org/tutorials) and the [Udacity Deep Learning with Pytorch repository](https://github.com/udacity/deep-learning-v2-pytorch/tree/master/intro-to-pytorch).

To begin, let's state the task at hand: _identifying text in an image_. In order to start this task, we will need a dataset that provides us text in image form. The MNIST dataset consists of greyscale handwritten digits 0-9 (see image below). Each image of a digit is 28x28 pixels.

![](https://raw.githubusercontent.com/udacity/deep-learning-v2-pytorch/3a95d118f9df5a86826e1791c5c100817f0fd924/intro-to-pytorch/assets/mnist.png "MNIST image examples")

We need to download this dataset from the `torchvision` package using the code below. This code will also create training and test datasets for us!

In [ ]:
from torchvision import datasets, transforms
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                              transforms.Normalize((0.5,), (0.5,)),
                              ])
# Download and load the training data
trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

testset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=False, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=True)

We will want to feed our images into the model one at a time, so we will use the iter() function to accomplish this goal:

In [ ]:
# Getting the data ready
dataiter = iter(trainloader)
images, labels = next(dataiter)

We should also know what our data look like:

In [ ]:
print(type(images))
print(images.shape)
print(labels.shape)

So now we see that each image is of 28x28 pixels, and there are 64 images in a batch. The 1 indicates that it's of one color scale (black-white).

Here's what one of the original images looks like:

In [ ]:
# Visualizing
import matplotlib.pyplot as plt
import numpy as np

plt.imshow(images[1].numpy().squeeze(), cmap='Greys_r');

We are now ready to build our model! Reminder: the goal of our model is to identify a piece of text (in this case, a number from 0-9) from an image. To accomplish this goal, we will create for a simple feed forward neural network (FFNN) with the following characteristics:

1. A Linear layer that takes in **784** inputs and outputs **256** hidden units
2. A Linear layer that takes in **256** hidden units and outputs **64** hidden units
3. A Linear layer that takes in **64** hidden units and outputs **10** output units
3. A softmax layer that determines the optimal label for the image (aka a number from 0-9)
4. A Rectified Linear Unit (ReLU) activation function

There are **2** ways to approach this:
1. Relying on the nn module as an abstraction
2. Staying more true to the math behind it all

In [ ]:
class ffnn(nn.Module):
    def __init__(self, ninp, nhid1, nhid2, nout):
        super().__init__()

        # Layers
        # self.embedding = nn.Embedding(num_dict, num_dim) #  Note that there isn't an embedding layer here! Why?
        self.input_hidden = nn.Linear(ninp, nhid1)              # One-hot to vector form, we already have a vector form so Linear is densifying
        self.hidden_hidden = nn.Linear(nhid1, nhid2)
        self.hidden_output = nn.Linear(nhid2, nout)

        # Functions
        self.relu = nn.ReLU()
        self.lsmax = nn.LogSoftmax()

    def forward(self, x):
        # Passing through first
        hid1 = self.input_hidden(x)
        hid1_relu = self.relu(hid1)                       # Note that the ReLU function doesn't "learn" anything. It's simply
                                                          # the activation function.
        # Passing through second
        hid2 = self.hidden_hidden(hid1_relu)
        hid2_relu = self.relu(hid2)

        # Getting output
        out = self.hidden_output(hid2_relu)

        return self.lsmax(out)    # Log Softmax!

    def show_layer_shapes(self):
        print(self.hidden1.shape)


In [ ]:
class ffnn2(nn.Module):
    def __init__(self, ninp, nhid1, nhid2, nout):
        super().__init__()

        # Layers
        # self.embedding = nn.Embedding(num_dict, num_dim) #  Note that there isn't an embedding layer here! Why?
        self.input_hidden = nn.Linear(ninp, nhid1)              # One-hot to vector form, we already have a vector form so Linear is densifying
        self.hidden_hidden = nn.Linear(nhid1, nhid2)
        self.hidden_output = nn.Linear(nhid2, nout)

    def forward(self, x):
        # Passing through first
        hid1 = self.input_hidden(x)
        hid1_relu = F.relu(hid1)                      # Note that the ReLU function doesn't "learn" anything. It's simply
                                                          # the activation function.
        # Passing through second
        hid2 = self.hidden_hidden(hid1_relu)
        hid2_relu = F.relu(hid2)                      # Can we change this to be an inplace function instead?
                                                      # If so, what would we need to change?
        # Getting output
        out = self.hidden_output(hid2_relu)

        return F.log_softmax(out, dim = 1)    # Log Softmax!

    def show_layer_shapes(self):
        print(self.input_hidden.weight.shape)
        print(self.hidden_hidden.weight.shape)
        print(self.hidden_output.weight.shape)

    def show_layer_gradients(self):
        print(self.input_hidden.weight.grad)


**Note on activation functions:** Broadly, activation functions inform our current layer about which neurons can pass on information to the next layer. An important characteristic of these activation functions is that they are *non-linear*. As the name suggests, non-linear activation functions allow our models to make predictions beyond those of simple linear ones, thus helping our models find more intricate patterns within our data and construct more complex representations. This often greatly improves model performance.

A number of non-linear activation functions exist (with PyTorch having many already [built-in](https://pytorch.org/docs/stable/nn.html#non-linear-activations-weighted-sum-nonlinearity). Some common ones are [Tanh](https://pytorch.org/docs/stable/generated/torch.nn.Tanh.html#torch.nn.Tanh), [Sigmoid](https://pytorch.org/docs/stable/generated/torch.nn.Sigmoid.html#torch.nn.Sigmoid), and [ReLU](https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html#torch.nn.ReLU). Try switching out ReLU with one of these other two to see how your model's performance changes!

We have just defined the model architecture for your FFNN! Great job :)

We will now initialize the model with the necessary dimensions for each layer (see above for dimensions), along with defining our loss criterion ([negative log-likelihood loss](https://pytorch.org/docs/stable/generated/torch.nn.NLLLoss.html)) and our optimizer ([stochastic gradient descent](https://pytorch.org/docs/stable/generated/torch.optim.SGD.html)). For our optimizer, we will also define a learning rate: this learning rate determines how quickly/slowly our model will update.



In [ ]:
from torch.autograd import Variable


model = ffnn2(784, 256, 64, 10)       # DECLARE THE MODEL... but why this model over the other one?
criterion = nn.NLLLoss()
optimizer = optim.SGD(model.parameters(), lr=0.003)

In [ ]:
# What do you think the output of this is?
model.show_layer_shapes()

Looks great, doesn't it? How do you think the model would perform if we ran it right now?

You got it: _very poorly_. We haven't passed it any training data yet! Let's change that. In the following code, we will pass all of the training data through the model 5 times (with each full pass through called an "epoch"). For each image, we'll:

1. zero our gradients to remove any leftovers from the previous training run
2. pass our data through the model
3. calculate the loss
4. perform backpropagation
4. implement our optimizer to tweak our model

That sounds like a _whole_ bunch of things to do, most of which also sound pretty complicated. Some good news: each of those steps is _**one**_ line of code!

Finally, after each epoch, we'll output our loss:

In [ ]:
epochs = 5
for e in range(epochs):
    running_loss = 0
    for images, labels in trainloader:
        # Flatten MNIST images into a 784 long vector
        images = images.view(images.shape[0], -1)
        #print(model.show_layer_gradiants())
        ###TO DO: Training pass###
        optimizer.zero_grad()             # First thing to do! Do NOT forget to do zero your gradients :)
        output = model.forward(images)    # Passing data through our model
        loss = criterion(output, labels)  # Calculating loss
        loss.backward()                   # Backpropagation isn't so scary after all!
        optimizer.step()                  # Performing SGD

        running_loss += loss.item()
    else:
        model.show_layer_gradients()
        print(f"Training loss for epoch {e}: {running_loss/len(trainloader)}")

**Note on loss criterion:** There are [a number of loss functions](https://pytorch.org/docs/stable/nn.html#loss-functions) that we can use to calculate how well our model predicted the intended labels. Common loss functions include Negative Log Likelihood, [Mean Squared Error](https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html#torch.nn.MSELoss), and [Cross Entropy](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss).

In the code above, we calculate the loss by weighing our model's predictions against the actual labels in `loss = criterion(output, labels)`. This loss is a tensor with all the necessary modifications to apply to our model. Afterward, we apply `loss.backward()` to calculate the gradients of these modifications, which we then apply to our model using the `optimizer.step()` line. Note that our `optimizer` takes in our model's parameters, meaning the `optimizer` knows where to make changes to the model according to the instructions from the `loss.backward()` step.

**Note on optimizer:** After each pass through the data, our optimizer will store all of the gradients. Since we do not want the information from the previous pass of data to additively affect our current model, we **must* zero our gradients. Please do not forget this step!



**Note on why the model isn't perfect after one epoch:** In class, a few students asked why our model doesn't just "learn everything in one pass". There are many different reasons, but I will outline two key ones here:

First, the data is noisy. My "2" is not the same as your "2", which is different than both Marty's and Lillian's "2"s. It is also extremely likely that each "2: I write is (at least) minorly different in appearance. However, our brains have identified the general, abstract image of what a "2" looks like -- "half a heart, with a line at the bottom going to the right" (or something like that) -- but such a conceptual representation can be realized as an image in infinite different ways. As such, our model is trying to "learn" this abstract form from the data, meaning it needs to discover some complex representation of pixels that identifies a "2" from an "8". With each pass through the data, the model becomes better and better at identifying the complex patterns that lead it to the abstract "2" class.

Second, the learning rate (here, lr = 0.003) determines how much the model can update at one point in time; learning rates are often between 0.01 and 0.001. The value of this learning rate matters quite a bit. If the learning rate is too high, the model will drastically change its parameters with each pass of the data, reducing the likelihood of model convergence because it cannot maintain its predictions. If the learning rate is too low, the model will make changes to its parameters that are too tiny, also reducing the likelihood that your model will converge, but for a different reason -- it may not reach the ideal local minima.

Note that our training loss goes down after each epoch -- this is good news! It means our model is becoming better at identifying the intended labels from the images it's receiving.


For now, let's say our model has been sufficiently trained (though feel free to mess with the architecture/training process to see how you can improve performance). It is now time to check our model's predictions on the test set.

The following three functions are for visualization purposes and do not have any effect on your model's training or testing:

In [ ]:
# Visualization function
def imshow(image, ax=None, title=None, normalize=True):
    """Imshow for Tensor."""
    if ax is None:
        fig, ax = plt.subplots()
    image = image.numpy().transpose((1, 2, 0))

    if normalize:
        mean = np.array([0.485, 0.456, 0.406])
        std = np.array([0.229, 0.224, 0.225])
        image = std * image + mean
        image = np.clip(image, 0, 1)

    ax.imshow(image)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_visible(False)
    ax.spines['bottom'].set_visible(False)
    ax.tick_params(axis='both', length=0)
    ax.set_xticklabels('')
    ax.set_yticklabels('')

    return ax

# Visualization function
def view_recon(img, recon):
    ''' Function for displaying an image (as a PyTorch Tensor) and its
        reconstruction also a PyTorch Tensor
    '''

    fig, axes = plt.subplots(ncols=2, sharex=True, sharey=True)
    axes[0].imshow(img.numpy().squeeze())
    axes[1].imshow(recon.data.numpy().squeeze())
    for ax in axes:
        ax.axis('off')
        ax.set_adjustable('box-forced')

# Visualization function
def view_classify(img, ps, version="MNIST"):
    ''' Function for viewing an image and it's predicted classes.
    '''
    ps = ps.data.numpy().squeeze()

    fig, (ax1, ax2) = plt.subplots(figsize=(6,9), ncols=2)
    ax1.imshow(img.resize_(1, 28, 28).numpy().squeeze())
    ax1.axis('off')
    ax2.barh(np.arange(10), ps)
    ax2.set_aspect(0.1)
    ax2.set_yticks(np.arange(10))
    if version == "MNIST":
        ax2.set_yticklabels(np.arange(10))
    elif version == "Fashion":
        ax2.set_yticklabels(['T-shirt/top',
                            'Trouser',
                            'Pullover',
                            'Dress',
                            'Coat',
                            'Sandal',
                            'Shirt',
                            'Sneaker',
                            'Bag',
                            'Ankle Boot'], size='small');
    ax2.set_title('Class Probability')
    ax2.set_xlim(0, 1.1)

    plt.tight_layout()

Let's see what we've got!

In [ ]:
%matplotlib inline

# Loading test data
images, labels = next(iter(testloader))

img = images[0].view(1, 784)
# Turn off gradients to speed up this part
with torch.no_grad():
    logps = model(img)

# Output of the network are log-probabilities, need to take exponential for probabilities
ps = torch.exp(logps)
view_classify(img.view(1, 28, 28), ps)

Congratulations!!! You've trained a model to identify text from an image.

**Note on why the model isn't perfect right away:** In class, a few students asked why our model doesn't just "learn everything in one pass". There are many different reasons, but I will outline two key ones here:

First, the data is noisy. My "2" is not the same as your "2", which is different than both Marty's and Lillian's "2"s. It is also extremely likely that each "2: I write is (at least) minorly different in appearance. However, our brains have identified the general, abstract image of what a "2" looks like -- "half a heart, with a line at the bottom going to the right" (or something like that) -- but such a conceptual representation can be realized as an image in infinite different ways. As such, our model is trying to "learn" this abstract form from the data, meaning it needs to discover some complex representation of pixels that identifies a "2" from an "8". With each pass through the data, the model becomes better and better at identifying the complex patterns that lead it to the abstract "2" class.

Second, we are controlling how much the model can update at once.

To perform additional test analyses (model perplexity, etc.), you can pass the entire test data through the model without updating any parameters or performing backpropagation and keep track of the total loss. However, this is a different task for another time... (cue mysterious music...).

Anyway, that's it for this tutorial! Hope it helps :)